name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set Timestamp
        run: echo "TIMESTAMP=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Get Short Commit Hash
        shell: bash
        run: echo "SHORT_HASH=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Run build.sh
        run: sh build.sh

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Latest Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Windows
          files: Surfing_windows-amd64_${{ env.SHORT_HASH }}.zip
          generate_release_notes: true
          body: |
            # Latest CI / Build
            自动同步分支最新代码以进行最新版本构建
            Release Timestamp: ${{ env.TIMESTAMP }}

            [![Download ${{ env.SHORT_HASH }}](https://img.shields.io/badge/Version%20Download-${{ env.SHORT_HASH }}-00b56a?style=flat-square&logo=git&logoColor=white)](https://github.com/GitMetaio/SurfingWin/releases/download/Windows/Surfing_windows-amd64_${{ env.SHORT_HASH }}.zip)

            **Full:** [Commits](https://github.com/GitMetaio/SurfingWin/commits/main)
